"""add_user_feedback

Revision ID: 0b4b7727bb9b
Revises: 002_add_reason_feedback
Create Date: 2026-06-03 09:28:17.531648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4b7727bb9b'
down_revision: Union[str, None] = '002_add_reason_feedback'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feedbacks_id'), 'user_feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_user_feedbacks_item_id'), 'user_feedbacks', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_feedbacks_user_id'), 'user_feedbacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_feedbacks_user_id'), table_name='user_feedbacks')
    op.drop_index(op.f('ix_user_feedbacks_item_id'), table_name='user_feedbacks')
    op.drop_index(op.f('ix_user_feedbacks_id'), table_name='user_feedbacks')
    op.drop_table('user_feedbacks')
    # ### end Alembic commands ###
